apiVersion: v1
kind: ServiceAccount
metadata:
  name: vigilante-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vigilante-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vigilante-rolebinding
subjects:
- kind: ServiceAccount
  name: vigilante-sa
roleRef:
  kind: Role
  name: vigilante-role
  apiGroup: rbac.authorization.k8s.io
