apiVersion: v1
kind: ServiceAccount
metadata:
  name: vigilante-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vigilante-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vigilante-rolebinding
subjects:
- kind: ServiceAccount
  name: vigilante-sa
roleRef:
  kind: Role
  name: vigilante-role
  apiGroup: rbac.authorization.k8s.io
