apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vigilante-metrics
  labels:
    app: vigilante
    app.kubernetes.io/name: vigilante
    app.kubernetes.io/instance: vigilante
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: qdrant-cluster
    release: prometheus
spec:
  selector:
    matchLabels:
      app: vigilante
      app.kubernetes.io/name: vigilante
      app.kubernetes.io/instance: vigilante
  endpoints:
  - port: http-metrics
    interval: 15s
    path: /metrics

