apiVersion: v1
kind: Service
metadata:
  name: vigilante-service
  labels:
    app: vigilante
spec:
  selector:
    app: vigilante
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: http-metrics
      port: 8080
      targetPort: 8080
  type: ClusterIP
